version: '3.8'

networks:
  amazon-net:
    driver: bridge

services:
  ms-gateway:
    image: ${ECR}/amazon-ms-gateway:latest
    container_name: ms-gateway
    restart: unless-stopped
    networks: [amazon-net]
    ports:
      - "8080:8080"
    environment:
      APP1_HOST: ${APP1_HOST}
      APP2_HOST: ${APP2_HOST}
      JAVA_OPTS: -Xmx256m

  front-end:
    image: ${ECR}/amazon-front:latest
    container_name: front-end
    restart: unless-stopped
    networks: [amazon-net]
    ports:
      - "80:8080"
    depends_on:
      - ms-gateway
