version: '3.8'

networks:
  amazon-net:
    driver: bridge

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8
    container_name: mysql-amazon
    networks: [amazon-net]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
