apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-end
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-auth
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-auth
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-cart
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-cart
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-gateway
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-gateway
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-inventory
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-inventory
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-notifications
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-notifications
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-orders
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-orders
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-payments
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-payments
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-products
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-products
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-reviews
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-reviews
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-search
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-search
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-shipping
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-shipping
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-users
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-users
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-wishlist
  namespace: amazon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-wishlist
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
