apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
  namespace: amazon
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/amazon-ms-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: DB_HOST
            - name: DB_NAME
              value: authdb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: JWT_SECRET
            - name: JAVA_OPTS
              value: "-Xmx256m"
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth
  namespace: amazon
spec:
  selector:
    app: ms-auth
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
