apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notifications
  namespace: amazon
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ms-notifications
  template:
    metadata:
      labels:
        app: ms-notifications
    spec:
      containers:
        - name: ms-notifications
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/amazon-ms-notifications:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: DB_HOST
            - name: DB_NAME
              value: notificationsdb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "localhost:9092"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: JAVA_OPTS
              value: "-Xmx256m"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-notifications
  namespace: amazon
spec:
  selector:
    app: ms-notifications
  ports:
    - port: 8089
      targetPort: 8089
  type: ClusterIP
