apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orders
  namespace: amazon
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ms-orders
  template:
    metadata:
      labels:
        app: ms-orders
    spec:
      containers:
        - name: ms-orders
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/amazon-ms-orders:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: DB_HOST
            - name: DB_NAME
              value: ordersdb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: JAVA_OPTS
              value: "-Xmx256m"
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-orders
  namespace: amazon
spec:
  selector:
    app: ms-orders
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
