apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-shipping
  namespace: amazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-shipping
  template:
    metadata:
      labels:
        app: ms-shipping
    spec:
      containers:
        - name: ms-shipping
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/amazon-ms-shipping:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: DB_HOST
            - name: DB_NAME
              value: shippingdb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amazon-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: JAVA_OPTS
              value: "-Xmx256m"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-shipping
  namespace: amazon
spec:
  selector:
    app: ms-shipping
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP
