server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: ms-auth
          uri: http://${APP1_HOST:ms-auth}:9000
          predicates:
            - Path=/api/auth/**

        - id: ms-users
          uri: http://${APP1_HOST:ms-users}:8082
          predicates:
            - Path=/api/users/**

        - id: ms-products
          uri: http://${APP1_HOST:ms-products}:8085
          predicates:
            - Path=/api/products/**

        - id: ms-cart
          uri: http://${APP1_HOST:ms-cart}:8087
          predicates:
            - Path=/api/cart/**

        - id: ms-wishlist
          uri: http://${APP1_HOST:ms-wishlist}:8092
          predicates:
            - Path=/api/wishlist/**

        - id: ms-search
          uri: http://${APP1_HOST:ms-search}:8091
          predicates:
            - Path=/api/search/**

        - id: ms-orders
          uri: http://${APP2_HOST:ms-orders}:8084
          predicates:
            - Path=/api/orders/**

        - id: ms-inventory
          uri: http://${APP2_HOST:ms-inventory}:8083
          predicates:
            - Path=/api/inventory/**

        - id: ms-payments
          uri: http://${APP2_HOST:ms-payments}:8086
          predicates:
            - Path=/api/payments/**

        - id: ms-shipping
          uri: http://${APP2_HOST:ms-shipping}:8088
          predicates:
            - Path=/api/shipping/**

        - id: ms-notifications
          uri: http://${APP2_HOST:ms-notifications}:8089
          predicates:
            - Path=/api/notifications/**

        - id: ms-reviews
          uri: http://${APP2_HOST:ms-reviews}:8090
          predicates:
            - Path=/api/reviews/**
