server.port=8090
spring.application.name=ms-reviews

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:reviewsdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:rootpass}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
