name: CI/CD ms-search

on:
  push:
    branches: [deploy]
    paths:
      - 'ms-search/**'
      - '.github/workflows/ms-search.yml'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push imagen
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/amazon-ms-search:$IMAGE_TAG -t $REGISTRY/amazon-ms-search:latest ./ms-search
          docker push $REGISTRY/amazon-ms-search:$IMAGE_TAG
          docker push $REGISTRY/amazon-ms-search:latest

      - name: Desplegar en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_APP1_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
            proxy_host: ${{ secrets.EC2_WEB_HOST }}
            proxy_username: ec2-user
            proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            cd ~/amazonfullstack
            docker compose pull ms-search
            docker compose up -d --no-deps ms-search
