name: CI/CD ms-wishlist

on:
  workflow_dispatch:
  push:
    branches: [deploy]
    paths:
      - 'ms-wishlist/**'
      - '.github/workflows/ms-wishlist.yml'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push imagen
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/amazon-ms-wishlist:$IMAGE_TAG -t $REGISTRY/amazon-ms-wishlist:latest ./ms-wishlist
          docker push $REGISTRY/amazon-ms-wishlist:$IMAGE_TAG
          docker push $REGISTRY/amazon-ms-wishlist:latest

      - name: Desplegar en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_WEB_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_APP1_HOST }} "
              aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com &&
              cd ~/amazonfullstack &&
              git pull origin deploy &&
              docker compose -f docker-compose.app1.yml --env-file .env pull ms-wishlist &&
              docker compose -f docker-compose.app1.yml --env-file .env up -d --no-deps ms-wishlist
            "
